name: Validate Files and code

on: 
    push:

jobs:
    validate-files:
        runs-on: ubuntu-latest
        steps:
            - name: get-repo-code
              uses: actions/checkout@v4

            - name: Validate html file
              run: test -f index.html
            
            - name: Validate js file
              run: test -f script.js
            